// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHIMAS_PREDICTIVE_ANALYTICS.Data;

#nullable disable

namespace PHIMAS_PREDICTIVE_ANALYTICS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312003016_SyncWithModel")]
    partial class SyncWithModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.HealthRecord", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<int?>("BHWID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HouseholdID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecordID");

                    b.ToTable("healthrecords", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Household", b =>
                {
                    b.Property<int>("HouseholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HouseholdID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HouseholdMember")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfMembers")
                        .HasColumnType("int");

                    b.Property<float?>("RiskScore")
                        .HasColumnType("float");

                    b.HasKey("HouseholdID");

                    b.ToTable("household", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Inventory", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MinimumThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ItemID");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.PredictiveAnalysis", b =>
                {
                    b.Property<int>("AnalyticsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnalyticsID"));

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HighRiskBarangay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PredictedCases")
                        .HasColumnType("int");

                    b.HasKey("AnalyticsID");

                    b.ToTable("predictiveanalysis", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReportID");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.TaskAssignment", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int?>("BHWID")
                        .HasColumnType("int");

                    b.Property<int?>("HouseholdID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TaskID");

                    b.ToTable("taskassignments", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
