// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHIMAS_PREDICTIVE_ANALYTICS.Data;

#nullable disable

namespace PHIMAS_PREDICTIVE_ANALYTICS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.HealthRecord", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<int>("BHWID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("RecordID");

                    b.HasIndex("BHWID");

                    b.HasIndex("PatientID");

                    b.ToTable("health_records", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Household", b =>
                {
                    b.Property<int>("HouseholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HouseholdID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float?>("RiskScore")
                        .HasColumnType("float");

                    b.HasKey("HouseholdID");

                    b.HasIndex("Address");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.HouseholdMember", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("HouseholdID")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmergencyContact")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MemberID");

                    b.HasIndex("HouseholdID", "FullName", "ContactNumber")
                        .IsUnique();

                    b.ToTable("household_members", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Inventory", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int?>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("MinimumThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ItemID");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.PredictiveAnalysis", b =>
                {
                    b.Property<int>("AnalyticsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnalyticsID"));

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HighRiskBarangay")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("PredictedCases")
                        .HasColumnType("int");

                    b.HasKey("AnalyticsID");

                    b.ToTable("predictive_analysis", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ReportID");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("PatientID");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.TaskAssignment", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskAssignmentID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int?>("BHWID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("HouseholdID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TaskID");

                    b.HasIndex("BHWID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("task_assignments", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AssignedArea")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.HealthRecord", b =>
                {
                    b.HasOne("PHIMAS_PREDICTIVE_ANALYTICS.Models.User", "BHW")
                        .WithMany()
                        .HasForeignKey("BHWID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PHIMAS_PREDICTIVE_ANALYTICS.Models.HouseholdMember", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BHW");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.HouseholdMember", b =>
                {
                    b.HasOne("PHIMAS_PREDICTIVE_ANALYTICS.Models.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Report", b =>
                {
                    b.HasOne("PHIMAS_PREDICTIVE_ANALYTICS.Models.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PHIMAS_PREDICTIVE_ANALYTICS.Models.HouseholdMember", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.TaskAssignment", b =>
                {
                    b.HasOne("PHIMAS_PREDICTIVE_ANALYTICS.Models.User", "BHW")
                        .WithMany()
                        .HasForeignKey("BHWID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PHIMAS_PREDICTIVE_ANALYTICS.Models.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BHW");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("PHIMAS_PREDICTIVE_ANALYTICS.Models.Household", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
